services:
  database:
    image: mariadb:11
    container_name: redm-vanilla-template-db
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "${MARIADB_HOST:-127.0.0.1}:${MARIADB_PORT:-3306}:3306"

    volumes:
      - redm-db-data:/var/lib/mysql

volumes:
  redm-db-data: